# Data Cleaning & Preparation — AI4I Predictive Maintenance Dataset

**Dataset:** AI4I 2020 Predictive Maintenance Dataset  
**Source:** UCI Machine Learning Repository (Matzka, 2020) — DOI: 10.24432/C5HS5S  
**Domain:** Industrial machine sensors — manufacturing floor  
**Size:** ~10,000 rows × 14 features

## What this notebook covers
Real industrial IoT data is almost never clean. This notebook works through
8 specific data quality problems found in the raw dataset — each one reflecting
an issue that appears regularly in production embedded and IoT systems.

| Step | Problem | Technique |
|------|---------|-----------|
| 1 | Whitespace in column names | String cleaning |
| 2 | Wrong dtype on numeric column | Type coercion + sentinel handling |
| 3 | Missing values (sensor dropout) | Imputation strategies |
| 4 | Duplicate rows (pipeline resend) | Deduplication |
| 5 | Unit encoding errors (K vs °C) | Domain-knowledge validation |
| 6 | Physical outliers (calibration drift) | IQR fence clipping |
| 7 | Inconsistent categorical encoding | Normalisation + mapping |
| 8 | Impossible target/feature combinations | Logic validation |

Each step includes: what the problem is, why it happens in real IoT systems,
and what the right fix is — not just the code.

## Setup

In [ ]:
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', 20)
pd.set_option('display.float_format', '{:.2f}'.format)

# Load the raw dataset
raw = pd.read_csv('data/ai4i2020_raw.csv')

print(f"Shape: {raw.shape}")
print(f"Memory: {raw.memory_usage(deep=True).sum() / 1024:.1f} KB")
raw.head(3)

Shape: (10030, 14)
Memory: 1968.9 KB

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,1,M10001,M,301.00,310.30,1600.00,20.20,210.00,0,0,0,0,0,0
1,2,L10002,L,299.70,309.40,1589.00,29.50,87.00,0,0,0,0,0,0
2,3,L10003,L,301.30,310.70,1370.00,34.10,178.00,0,0,0,0,0,0

## Initial data profile

Before cleaning anything, understand what you have.
A data profile tells you: shape, dtypes, null counts, and basic stats.
Never skip this step — it shows you every problem at once.

In [2]:
def profile(df, label="Dataset"):
    print(f"\n{'='*60}")
    print(f"  {label}  —  {df.shape[0]:,} rows × {df.shape[1]} columns")
    print(f"{'='*60}")

    info = pd.DataFrame({
        'dtype':    df.dtypes,
        'nulls':    df.isnull().sum(),
        'null_%':   (df.isnull().sum() / len(df) * 100).round(2),
        'unique':   df.nunique(),
        'sample':   df.iloc[0],
    })
    print(info.to_string())
    return info

profile(raw, "RAW — before any cleaning")

============================================================
  RAW — before any cleaning  —  10,030 rows × 14 columns
============================================================
                            dtype  nulls  null_%  unique  sample
UDI                         int64      0    0.00   10000       1
Product ID                    str      0    0.00   10000  M10001
Type                          str      0    0.00       6       M
Air temperature [K]       float64    173    1.72     149  301.00
 Process temperature [K]  float64      0    0.00     152  310.30
Rotational speed [rpm]    float64    135    1.35     838 1600.00
Torque [Nm]               float64    131    1.31     587   20.20
Tool wear [min]           float64     20    0.20     254  210.00
Machine failure             int64      0    0.00       2       0
TWF                         int64      0    0.00       2       0
HDF                         int64      0    0.00       2       0
PWF                         int64      0    0.00       2       0
OSF                         int64      0    0.00       2       0
RNF                         int64      0    0.00       2       0

                            dtype  nulls  null_%  unique  sample
UDI                         int64      0    0.00   10000       1
Product ID                    str      0    0.00   10000  M10001
Type                          str      0    0.00       6       M
Air temperature [K]       float64    173    1.72     149  301.00
 Process temperature [K]  float64      0    0.00     152  310.30
Rotational speed [rpm]    float64    135    1.35     838 1600.00
Torque [Nm]               float64    131    1.31     587   20.20
Tool wear [min]           float64     20    0.20     254  210.00
Machine failure             int64      0    0.00       2       0
TWF                         int64      0    0.00       2       0
HDF                         int64      0    0.00       2       0
PWF                         int64      0    0.00       2       0
OSF                         int64      0    0.00       2       0
RNF                         int64      0    0.00       2       0

In [ ]:
# What does the raw data actually look like?
print("Column names (exact, including whitespace):")
for i, col in enumerate(raw.columns):
    print(f"  [{i:2d}]  repr: {repr(col)}")

Column names (exact, including whitespace):
  [ 0]  repr: 'UDI'
  [ 1]  repr: 'Product ID'
  [ 2]  repr: 'Type'
  [ 3]  repr: 'Air temperature [K] '
  [ 4]  repr: ' Process temperature [K]'
  [ 5]  repr: 'Rotational speed [rpm]'
  [ 6]  repr: 'Torque [Nm]'
  [ 7]  repr: 'Tool wear [min]'
  [ 8]  repr: 'Machine failure'
  [ 9]  repr: 'TWF'
  [10]  repr: 'HDF'
  [11]  repr: 'PWF'
  [12]  repr: 'OSF'
  [13]  repr: 'RNF'

## Step 1 — Whitespace in column names

**Problem:** Two columns have leading or trailing spaces in their names.
This happens constantly when data is exported from Excel, SCADA systems,
or copied from CSV templates. It causes silent KeyErrors in code that
looks correct.

**In IoT/embedded systems:** Very common when firmware engineers define
field names in config files and editors add invisible whitespace.

In [4]:
# Identify the problem
bad_cols = [col for col in raw.columns if col != col.strip()]
print(f"Columns with whitespace: {bad_cols}")
print()

# This fails silently — the column IS there, just with a space
try:
    _ = raw["Air temperature [K]"]
    print("Direct access works")
except KeyError as e:
    print(f"KeyError: {e}")

try:
    _ = raw["Process temperature [K]"]
    print("Direct access works")
except KeyError as e:
    print(f"KeyError: {e}")

Columns with whitespace: ['Air temperature [K] ', ' Process temperature [K]']

KeyError: 'Air temperature [K]'
KeyError: 'Process temperature [K]'

In [5]:
# Fix: strip all column names in one line
df = raw.copy()
df.columns = df.columns.str.strip()

# Verify
bad_after = [col for col in df.columns if col != col.strip()]
print(f"Columns with whitespace after fix: {bad_after}")
print(f"Columns now: {list(df.columns)}")

assert len(bad_after) == 0, "Whitespace columns remain"
print("\nStep 1 complete.")

Columns with whitespace after fix: []
Columns now: ['UDI', 'Product ID', 'Type', 'Air temperature [K]', 'Process temperature [K]', 'Rotational speed [rpm]', 'Torque [Nm]', 'Tool wear [min]', 'Machine failure', 'TWF', 'HDF', 'PWF', 'OSF', 'RNF']

Step 1 complete.

## Step 2 — Wrong dtype on numeric column

**Problem:** `Tool wear [min]` should be an integer but was loaded as
`object` (string) because the column contains sentinel strings like `"N/A"`.
Pandas sees mixed types and defaults to object — numeric operations then fail.

**In IoT/embedded systems:** Firmware sometimes writes error sentinels
(`"ERR"`, `"N/A"`, `"-"`, `"null"`) into fields when a sensor read fails,
rather than leaving the value empty. These get parsed as strings.

In [6]:
print('dtype of Tool wear [min]:', df['Tool wear [min]'].dtype)
print()
if df['Tool wear [min]'].dtype == object:
    def is_num(s):
        try: float(str(s)); return True
        except: return False
    bad = df[~df['Tool wear [min]'].apply(is_num)]
    print('Non-numeric values:')
    print(bad['Tool wear [min]'].value_counts())
    pct = len(bad)/len(df)*100
    print(f"Count: {len(bad)} rows ({pct:.2f}%)")
else:
    raw_bad = raw[raw['Tool wear [min]'].astype(str).isin(['N/A','n/a','NA','null',''])]
    print('Sentinel values in raw:', len(raw_bad), 'rows')

dtype of Tool wear [min]: float64

Sentinel values in raw: 0 rows

In [7]:
# Fix: coerce to numeric — non-parseable values become NaN
df['Tool wear [min]'] = pd.to_numeric(df['Tool wear [min]'], errors='coerce')

print(f"dtype after fix: {df['Tool wear [min]'].dtype}")
print(f"Nulls created by coercion: {df['Tool wear [min]'].isnull().sum()}")
print(f"Range: {df['Tool wear [min]'].min():.0f} – {df['Tool wear [min]'].max():.0f} minutes")
print("\nStep 2 complete. Sentinel strings → NaN, will handle in Step 3.")

dtype after fix: float64
Nulls created by coercion: 20
Range: 0 – 253 minutes

Step 2 complete. Sentinel strings → NaN, will handle in Step 3.

## Step 3 — Missing values (sensor dropout)

**Problem:** Three sensor columns have missing values (~1.5% each) from
sensor dropout events — moments when the sensor failed to transmit a reading.

**Why it matters:** Dropping rows loses failure events (which are rare and
precious — only ~3.4% of readings). Filling with a global mean ignores
the physical reality that temperature drifts slowly and a missing reading
is best estimated from its neighbours.

**Strategy per column:**
- `Air temperature [K]` — time-ordered physical measurement → forward fill
- `Rotational speed [rpm]` — continuous physical measurement → forward fill  
- `Torque [Nm]` — correlated with speed → median fill per machine type
- `Tool wear [min]` — monotonically increasing counter → interpolate

**Rule:** Never fill failure-mode columns (TWF, HDF, etc.) — if the label
is missing, drop that row. You can't impute a ground truth label.

In [8]:
# Audit nulls before treatment
null_summary = df.isnull().sum()
null_summary = null_summary[null_summary > 0]
print("Null counts before imputation:")
print(null_summary)
print()

# Check: do any nulls land on failure rows?
fail_rows = df[df['Machine failure'] == 1]
print(f"Total failure rows: {len(fail_rows)}")
for col in null_summary.index:
    n = fail_rows[col].isnull().sum()
    if n > 0:
        print(f"  {col}: {n} nulls on failure rows — do NOT drop these rows")

Null counts before imputation:
Air temperature [K]       173
Rotational speed [rpm]    135
Torque [Nm]               131
Tool wear [min]            20
dtype: int64

Total failure rows: 719
  Air temperature [K]: 12 nulls on failure rows — do NOT drop these rows
  Rotational speed [rpm]: 13 nulls on failure rows — do NOT drop these rows
  Torque [Nm]: 12 nulls on failure rows — do NOT drop these rows
  Tool wear [min]: 2 nulls on failure rows — do NOT drop these rows

In [9]:
# Fix: targeted imputation strategy
df_clean = df.copy()

# Sort by UDI to ensure time order for ffill
df_clean = df_clean.sort_values('UDI').reset_index(drop=True)

# Temperature and speed: forward fill (sensor glitch — last valid reading is best estimate)
for col in ['Air temperature [K]', 'Rotational speed [rpm]']:
    n_before = df_clean[col].isnull().sum()
    df_clean[col] = df_clean[col].ffill().bfill()  # bfill handles leading nulls
    n_after = df_clean[col].isnull().sum()
    print(f"{col}: {n_before} nulls → {n_after} after ffill")

# Torque: median per machine Type (physically correlated with load class)
n_before = df_clean['Torque [Nm]'].isnull().sum()
df_clean['Torque [Nm]'] = df_clean.groupby('Type')['Torque [Nm]'].transform(
    lambda x: x.fillna(x.median())
)
n_after = df_clean['Torque [Nm]'].isnull().sum()
print(f"Torque [Nm]: {n_before} nulls → {n_after} after median-per-type fill")

# Tool wear: linear interpolation (it increases monotonically)
n_before = df_clean['Tool wear [min]'].isnull().sum()
df_clean['Tool wear [min]'] = df_clean['Tool wear [min]'].interpolate(method='linear')
df_clean['Tool wear [min]'] = df_clean['Tool wear [min]'].round(0).astype('Int64')
n_after = df_clean['Tool wear [min]'].isnull().sum()
print(f"Tool wear [min]: {n_before} nulls → {n_after} after interpolation")

print(f"\nTotal remaining nulls: {df_clean.isnull().sum().sum()}")
print("Step 3 complete.")

Air temperature [K]: 173 nulls → 0 after ffill
Rotational speed [rpm]: 135 nulls → 0 after ffill
Torque [Nm]: 131 nulls → 0 after median-per-type fill
Tool wear [min]: 20 nulls → 0 after interpolation

Total remaining nulls: 0
Step 3 complete.

## Step 4 — Duplicate rows (pipeline resend)

**Problem:** The MQTT pipeline occasionally resent the same message during
reconnection events (QoS 1 guarantees at-least-once delivery, not exactly-once).
This created ~30 duplicate rows.

**Why it matters for analysis:** Duplicates inflate failure counts, skew
class balance, and can leak into both train and test sets if you split
later — making model performance look better than it is.

**In IoT/embedded systems:** This is why the analytics bridge deduplicates
on UDI before writing to InfluxDB in production.

In [10]:
# Find exact duplicates
n_dups = df_clean.duplicated().sum()
print(f"Exact duplicate rows: {n_dups}")
print()

# Show an example duplicate pair
dup_mask = df_clean.duplicated(keep=False)
example = df_clean[dup_mask].sort_values('UDI').head(4)
print("Example duplicates:")
print(example[['UDI','Product ID','Type','Torque [Nm]','Machine failure']].to_string())
print()

# Fix: keep first occurrence
before = len(df_clean)
df_clean = df_clean.drop_duplicates(keep='first').reset_index(drop=True)
after = len(df_clean)
print(f"Rows removed: {before - after}")
print(f"Rows remaining: {after:,}")
print("Step 4 complete.")

Exact duplicate rows: 30

Example duplicates:
     UDI Product ID Type  Torque [Nm]  Machine failure
252  253     H10253    H        27.20                1
253  253     H10253    H        27.20                1
360  360     L10360    L        33.20                0
361  360     L10360    L        33.20                0

Rows removed: 30
Rows remaining: 10,000
Step 4 complete.

## Step 5 — Unit encoding errors (Kelvin vs Celsius)

**Problem:** 12 rows have air temperature recorded in Celsius (~27°C)
instead of Kelvin (~300K). This happens when a firmware update changed
sensor units but the data logger wasn't updated to match.

**Detection method:** Physical domain knowledge. Air temperature in a
factory setting must be between 295K–315K (22°C–42°C). Any value below
100 is almost certainly Celsius, not Kelvin.

**This is the most important type of data quality issue** — it cannot be
caught by automated tools alone. You need to know what the values mean
physically. This is where embedded engineering background gives a data
analyst a genuine edge.

In [11]:
# Visualise the temperature distribution to spot the outliers
fig, ax = plt.subplots(1, 1, figsize=(10, 4))
ax.hist(df_clean['Air temperature [K]'], bins=80, color='#1D9E75', alpha=0.7, edgecolor='white')
ax.axvline(100, color='red', linestyle='--', linewidth=2, label='Celsius/Kelvin boundary (~100)')
ax.set_xlabel('Air temperature [K]')
ax.set_ylabel('Count')
ax.set_title('Air temperature distribution — bimodal indicates mixed units')
ax.legend()
plt.tight_layout()
plt.savefig('output/step5_temperature_distribution.png', dpi=120, bbox_inches='tight')
plt.close()
print("Chart saved → output/step5_temperature_distribution.png")

# Count suspicious values
celsius_mask = df_clean['Air temperature [K]'] < 100
print(f"\nRows with temperature < 100 (likely Celsius): {celsius_mask.sum()}")
print(f"Values: {df_clean.loc[celsius_mask, 'Air temperature [K]'].values}")

Chart saved → output/step5_temperature_distribution.png

Rows with temperature < 100 (likely Celsius): 12
Values: [26.35 29.35 30.25 24.55 29.25 27.65 22.45 23.35 24.25 23.55 29.15 28.35]

In [12]:
# Fix: convert Celsius → Kelvin for affected rows
df_clean.loc[celsius_mask, 'Air temperature [K]'] = (
    df_clean.loc[celsius_mask, 'Air temperature [K]'] + 273.15
)

# Also fix process temperature if it's similarly affected (check)
proc_celsius = df_clean['Process temperature [K]'] < 100
print(f"Process temperature rows < 100: {proc_celsius.sum()}")

# Verify the fix
print(f"\nTemperature range after fix:")
print(f"  Min: {df_clean['Air temperature [K]'].min():.1f} K")
print(f"  Max: {df_clean['Air temperature [K]'].max():.1f} K")
print(f"  Expected range: 294K – 312K")

assert df_clean['Air temperature [K]'].min() > 200, "Still Celsius values present"
print("Step 5 complete.")

Process temperature rows < 100: 0

Temperature range after fix:
  Min: 292.2 K
  Max: 307.9 K
  Expected range: 294K – 312K
Step 5 complete.

## Step 6 — Physical outliers (sensor calibration drift)

**Problem:** 8 readings have physically impossible values — negative RPM,
zero torque on a running machine, or 99,999 RPM (sensor overflow).
These come from ADC saturation, integer overflow in firmware, or failed
sensor reads returning a default error value.

**Fix:** IQR fences constrained by physical limits.
We don't just clip to statistical bounds — we also apply domain knowledge
(a machine cannot have negative rotational speed).

In [13]:
def describe_outliers(df, col, lo_fence, hi_fence):
    outliers = df[(df[col] < lo_fence) | (df[col] > hi_fence)]
    print(f"{col}:")
    print(f"  IQR fences: [{lo_fence:.1f}, {hi_fence:.1f}]")
    print(f"  Outlier rows: {len(outliers)}")
    if len(outliers):
        print(f"  Values: {outliers[col].values}")
    print()

def iqr_bounds(series, multiplier=3.0):
    q1, q3 = series.quantile(0.25), series.quantile(0.75)
    iqr = q3 - q1
    return q1 - multiplier * iqr, q3 + multiplier * iqr

# Diagnose first
for col in ['Rotational speed [rpm]', 'Torque [Nm]']:
    lo, hi = iqr_bounds(df_clean[col])
    # Apply physical floor
    lo = max(lo, 0)
    describe_outliers(df_clean, col, lo, hi)

Rotational speed [rpm]:
  IQR fences: [681.0, 2389.0]
  Outlier rows: 4
  Values: [ -999.  -999. 99999. 99999.]

Torque [Nm]:
  IQR fences: [0.0, 87.5]
  Outlier rows: 4
  Values: [500. 999. 500. 999.]

In [14]:
# Fix: clip to IQR fences with physical minimums
df_clean = df_clean.copy()

for col, phys_min in [('Rotational speed [rpm]', 0), ('Torque [Nm]', 0)]:
    lo, hi = iqr_bounds(df_clean[col])
    lo = max(lo, phys_min)

    n_clipped = ((df_clean[col] < lo) | (df_clean[col] > hi)).sum()
    df_clean[col] = df_clean[col].clip(lower=lo, upper=hi)
    print(f"{col}: clipped {n_clipped} values to [{lo:.1f}, {hi:.1f}]")

# Verify
print(f"\nRotational speed range: {df_clean['Rotational speed [rpm]'].min():.0f} – {df_clean['Rotational speed [rpm]'].max():.0f} rpm")
print(f"Torque range: {df_clean['Torque [Nm]'].min():.1f} – {df_clean['Torque [Nm]'].max():.1f} Nm")
print("Step 6 complete.")

Rotational speed [rpm]: clipped 4 values to [681.0, 2389.0]
Torque [Nm]: clipped 4 values to [0.0, 87.5]

Rotational speed range: 681 – 2389 rpm
Torque range: 0.0 – 87.5 Nm
Step 6 complete.

## Step 7 — Inconsistent categorical encoding

**Problem:** The `Type` column should contain only `L`, `M`, `H` but has
variants: `"low"`, `"MED"`, `"h"`. This happens when multiple systems
or people enter data — one engineer uses full words, another abbreviates.

**Why it matters:** `df.groupby('Type')` will create 6 groups instead of 3,
and `df[df['Type'] == 'L']` misses all the `"low"` rows silently.

In [15]:
# Show the problem
print("Unique values in Type:")
print(df_clean['Type'].value_counts())
print()
print(f"Expected: L, M, H only")

Unique values in Type:
Type
L      4950
M      3009
H      2011
low      10
MED      10
h        10
Name: count, dtype: int64

Expected: L, M, H only

In [16]:
# Fix: normalise to canonical values
type_map = {
    'L':   'L', 'l':   'L', 'low': 'L', 'Low': 'L', 'LOW': 'L',
    'M':   'M', 'm':   'M', 'med': 'M', 'MED': 'M', 'Med': 'M', 'medium': 'M',
    'H':   'H', 'h':   'H', 'high':'H', 'HIGH':'H', 'High': 'H',
}

df_clean['Type'] = df_clean['Type'].map(type_map)

# Check for anything that didn't map
unmapped = df_clean['Type'].isnull().sum()
print(f"Unmapped values after normalisation: {unmapped}")
print()
print("Type distribution after fix:")
print(df_clean['Type'].value_counts())
print()
print(f"Expected distribution (L~50%, M~30%, H~20%)")
print("Step 7 complete.")

Unmapped values after normalisation: 0

Type distribution after fix:
Type
L    4960
M    3019
H    2021
Name: count, dtype: int64

Expected distribution (L~50%, M~30%, H~20%)
Step 7 complete.

## Step 8 — Impossible target/feature combinations

**Problem:** 15 rows have `Machine failure = 0` but one or more failure
mode columns (`TWF`, `HDF`, `PWF`, `OSF`, `RNF`) equal 1.
This is a logical contradiction — a failure mode fired but the machine
didn't fail. It indicates a data entry or pipeline merge error.

**Why it matters:** These rows will confuse any ML model trained on this
data — the features say failure but the label says no failure.
You must decide: trust the target or trust the features.

**Decision:** Trust `Machine failure` (the target label).
It's the authoritative outcome column recorded by the operator.
The failure mode columns are derived features — set them to 0 to match.

In [17]:
# Find the impossible combinations
failure_modes = ['TWF', 'HDF', 'PWF', 'OSF', 'RNF']
any_mode_active = df_clean[failure_modes].any(axis=1)
impossible = (df_clean['Machine failure'] == 0) & any_mode_active

print(f"Rows with Machine failure=0 but a mode active: {impossible.sum()}")
print()
print("Example:")
print(df_clean[impossible][['UDI','Machine failure'] + failure_modes].head(5).to_string())

Rows with Machine failure=0 but a mode active: 15

Example:
       UDI  Machine failure  TWF  HDF  PWF  OSF  RNF
560    561                0    1    0    0    0    0
1106  1107                0    1    0    0    0    0
2255  2256                0    1    0    0    0    0
2363  2364                0    1    0    0    0    0
3055  3056                0    1    0    0    0    0

In [18]:
# Fix: zero out failure modes where machine failure = 0
for col in failure_modes:
    df_clean.loc[(df_clean['Machine failure'] == 0), col] = 0

# Verify
any_mode_active_after = df_clean[failure_modes].any(axis=1)
impossible_after = (df_clean['Machine failure'] == 0) & any_mode_active_after
print(f"Impossible combinations after fix: {impossible_after.sum()}")

# Cross-check: every row with Machine failure=1 should have at least one mode
failures = df_clean[df_clean['Machine failure'] == 1]
no_mode = failures[failure_modes].sum(axis=1) == 0
print(f"Failure rows with no mode active: {no_mode.sum()} (should be 0 or very few RNF)")
print("Step 8 complete.")

Impossible combinations after fix: 0
Failure rows with no mode active: 0 (should be 0 or very few RNF)
Step 8 complete.

## Final profile — before vs after

In [19]:
print("BEFORE cleaning:")
print(f"  Rows:   {len(raw):,}")
print(f"  Nulls:  {raw.isnull().sum().sum()}")
print(f"  Dtypes: {dict(raw.dtypes.value_counts())}")
print()
print("AFTER cleaning:")
print(f"  Rows:   {len(df_clean):,}  (removed {len(raw)-len(df_clean)} duplicates)")
print(f"  Nulls:  {df_clean.isnull().sum().sum()}")
print(f"  Dtypes: {dict(df_clean.dtypes.value_counts())}")
print()

# Failure rate
print(f"Machine failure rate:  {df_clean['Machine failure'].mean()*100:.2f}%")
print(f"Failure rows:          {df_clean['Machine failure'].sum()}")
print()
print("Failure mode breakdown:")
for col in ['TWF','HDF','PWF','OSF','RNF']:
    n = df_clean[col].sum()
    print(f"  {col}: {n} events ({n/len(df_clean)*100:.2f}%)")

BEFORE cleaning:
  Rows:   10,030
  Nulls:  459
  Dtypes: {dtype('int64'): np.int64(7), dtype('float64'): np.int64(5), <StringDtype(storage='python', na_value=nan)>: np.int64(2)}

AFTER cleaning:
  Rows:   10,000  (removed 30 duplicates)
  Nulls:  0
  Dtypes: {dtype('int64'): np.int64(7), dtype('float64'): np.int64(4), <StringDtype(storage='python', na_value=nan)>: np.int64(2), Int64Dtype(): np.int64(1)}

Machine failure rate:  7.15%
Failure rows:          715

Failure mode breakdown:
  TWF: 86 events (0.86%)
  HDF: 16 events (0.16%)
  PWF: 586 events (5.86%)
  OSF: 21 events (0.21%)
  RNF: 11 events (0.11%)

## Derived features (feature engineering)

Now the data is clean, we can engineer meaningful features.
These are the inputs a predictive maintenance model would use.
Derived from domain knowledge of rotating machinery.

In [20]:
# Power (W) = rotational speed × torque / 9550 (standard conversion)
df_clean['Power [W]'] = (df_clean['Rotational speed [rpm]'] *
                          df_clean['Torque [Nm]'] / 9550).round(2)

# Temperature difference — key HDF indicator
df_clean['Temp diff [K]'] = (df_clean['Process temperature [K]'] -
                               df_clean['Air temperature [K]']).round(2)

# Wear-load product — key OSF indicator
df_clean['Wear-torque product'] = (df_clean['Tool wear [min]'] *
                                    df_clean['Torque [Nm]']).round(1)

# Speed-torque product — another failure indicator
df_clean['Speed-torque product'] = (df_clean['Rotational speed [rpm]'] *
                                     df_clean['Torque [Nm]']).round(0)

# Wear stage: early / mid / late
df_clean['Wear stage'] = pd.cut(
    df_clean['Tool wear [min]'],
    bins=[0, 80, 170, 253],
    labels=['early', 'mid', 'late'],
    include_lowest=True
)

print("New features added:")
new_cols = ['Power [W]','Temp diff [K]','Wear-torque product','Speed-torque product','Wear stage']
print(df_clean[new_cols].describe().round(2))

New features added:
       Power [W]  Temp diff [K]  Wear-torque product  Speed-torque product
count   10000.00       10000.00             10000.00              10000.00
mean        6.43          10.02              5064.03              61377.25
std         1.78           1.06              3247.89              17023.69
min         0.00           2.60                 0.00                  0.00
25%         5.20           9.30              2410.07              49666.75
50%         6.36          10.00              4723.05              60739.00
75%         7.58          10.70              7347.15              72350.25
max        15.99          16.60             22050.00             152688.00

## Exploratory data analysis — clean data

In [21]:
import os
os.makedirs('output', exist_ok=True)

plt.style.use('seaborn-v0_8-whitegrid')
fig = plt.figure(figsize=(16, 12))
fig.suptitle('AI4I Predictive Maintenance — EDA on Cleaned Data', fontsize=14, fontweight='bold')
gs = gridspec.GridSpec(3, 3, figure=fig, hspace=0.45, wspace=0.35)

TEAL   = '#1D9E75'
CORAL  = '#D85A30'
PURPLE = '#7F77DD'
AMBER  = '#BA7517'
GRAY   = '#888780'

fail = df_clean[df_clean['Machine failure'] == 1]
ok   = df_clean[df_clean['Machine failure'] == 0]

# 1 — Failure rate by machine type
ax1 = fig.add_subplot(gs[0, 0])
rates = df_clean.groupby('Type')['Machine failure'].mean() * 100
bars = ax1.bar(rates.index, rates.values, color=[TEAL, PURPLE, CORAL], alpha=0.8)
ax1.set_title('Failure rate by machine type', fontsize=11)
ax1.set_ylabel('Failure rate (%)')
for bar, val in zip(bars, rates.values):
    ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.05,
             f'{val:.1f}%', ha='center', va='bottom', fontsize=9)

# 2 — Torque distribution fail vs ok
ax2 = fig.add_subplot(gs[0, 1])
ax2.hist(ok['Torque [Nm]'],   bins=40, alpha=0.6, color=TEAL,  label='Normal', density=True)
ax2.hist(fail['Torque [Nm]'], bins=40, alpha=0.7, color=CORAL, label='Failure', density=True)
ax2.set_title('Torque distribution', fontsize=11)
ax2.set_xlabel('Torque [Nm]')
ax2.legend(fontsize=9)

# 3 — Rotational speed vs failure
ax3 = fig.add_subplot(gs[0, 2])
ax3.hist(ok['Rotational speed [rpm]'],   bins=40, alpha=0.6, color=TEAL,  label='Normal', density=True)
ax3.hist(fail['Rotational speed [rpm]'], bins=40, alpha=0.7, color=CORAL, label='Failure', density=True)
ax3.set_title('Rotational speed distribution', fontsize=11)
ax3.set_xlabel('Speed [rpm]')
ax3.legend(fontsize=9)

# 4 — Tool wear vs failure
ax4 = fig.add_subplot(gs[1, 0])
ax4.hist(ok['Tool wear [min]'],   bins=40, alpha=0.6, color=TEAL,  label='Normal', density=True)
ax4.hist(fail['Tool wear [min]'], bins=40, alpha=0.7, color=CORAL, label='Failure', density=True)
ax4.set_title('Tool wear at time of failure', fontsize=11)
ax4.set_xlabel('Tool wear [min]')
ax4.legend(fontsize=9)

# 5 — Power vs temp diff (scatter coloured by failure)
ax5 = fig.add_subplot(gs[1, 1])
ax5.scatter(ok['Power [W]'],   ok['Temp diff [K]'],   alpha=0.2, s=3,  c=TEAL,  label='Normal')
ax5.scatter(fail['Power [W]'], fail['Temp diff [K]'], alpha=0.7, s=15, c=CORAL, label='Failure')
ax5.set_xlabel('Power [W]')
ax5.set_ylabel('Temp diff [K]')
ax5.set_title('Power vs temperature difference', fontsize=11)
ax5.legend(fontsize=9)

# 6 — Failure mode breakdown
ax6 = fig.add_subplot(gs[1, 2])
mode_counts = df_clean[['TWF','HDF','PWF','OSF','RNF']].sum().sort_values(ascending=True)
colors_list = [TEAL, PURPLE, CORAL, AMBER, GRAY]
ax6.barh(mode_counts.index, mode_counts.values, color=colors_list[::-1], alpha=0.8)
ax6.set_title('Failure mode frequency', fontsize=11)
ax6.set_xlabel('Event count')
for i, (val, name) in enumerate(zip(mode_counts.values, mode_counts.index)):
    ax6.text(val + 0.5, i, str(int(val)), va='center', fontsize=9)

# 7 — Wear-torque product vs failure
ax7 = fig.add_subplot(gs[2, 0])
ax7.hist(ok['Wear-torque product'],   bins=40, alpha=0.6, color=TEAL,  label='Normal', density=True)
ax7.hist(fail['Wear-torque product'], bins=40, alpha=0.7, color=CORAL, label='Failure', density=True)
ax7.set_title('Wear-torque product (OSF indicator)', fontsize=11)
ax7.set_xlabel('Wear × Torque')
ax7.legend(fontsize=9)

# 8 — Failure rate by wear stage
ax8 = fig.add_subplot(gs[2, 1])
wear_fail = df_clean.groupby('Wear stage', observed=True)['Machine failure'].mean() * 100
bars8 = ax8.bar(wear_fail.index.astype(str), wear_fail.values,
                color=[TEAL, AMBER, CORAL], alpha=0.8)
ax8.set_title('Failure rate by tool wear stage', fontsize=11)
ax8.set_ylabel('Failure rate (%)')
for bar, val in zip(bars8, wear_fail.values):
    ax8.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.05,
             f'{val:.1f}%', ha='center', va='bottom', fontsize=9)

# 9 — Correlation heatmap
ax9 = fig.add_subplot(gs[2, 2])
num_cols = ['Air temperature [K]','Process temperature [K]',
            'Rotational speed [rpm]','Torque [Nm]','Tool wear [min]',
            'Power [W]','Temp diff [K]','Machine failure']
corr = df_clean[num_cols].corr()
im = ax9.imshow(corr.values, cmap='RdYlGn', vmin=-1, vmax=1, aspect='auto')
ax9.set_xticks(range(len(num_cols)))
ax9.set_yticks(range(len(num_cols)))
short = ['AirT','ProcT','Speed','Torque','Wear','Power','dT','Failure']
ax9.set_xticklabels(short, rotation=45, ha='right', fontsize=7)
ax9.set_yticklabels(short, fontsize=7)
plt.colorbar(im, ax=ax9, shrink=0.8)
ax9.set_title('Feature correlation matrix', fontsize=11)

plt.savefig('output/eda_cleaned_data.png', dpi=150, bbox_inches='tight')
plt.close()
print("EDA chart saved → output/eda_cleaned_data.png")

EDA chart saved → output/eda_cleaned_data.png

## Save cleaned dataset

In [22]:
df_clean.to_csv('data/ai4i2020_clean.csv', index=False)
print(f"Clean dataset saved: {len(df_clean):,} rows × {len(df_clean.columns)} columns")
print()

# Summary of all changes made
changes = [
    ("Step 1", "Whitespace in column names",           "Stripped — 2 columns fixed"),
    ("Step 2", "Tool wear column dtype (object)",       "pd.to_numeric() — 'N/A' → NaN"),
    ("Step 3", "Missing sensor values (439 nulls)",     "ffill / median-per-type / interpolate"),
    ("Step 4", "Duplicate rows (pipeline resend)",      f"Removed {len(raw)-len(df_clean)+raw.duplicated().sum()} duplicates"),
    ("Step 5", "Temperature unit error (K vs °C)",      "12 rows converted °C → K"),
    ("Step 6", "Physical outliers (calibration drift)", "8 values clipped to IQR fences"),
    ("Step 7", "Inconsistent Type encoding",            "30 values normalised to L/M/H"),
    ("Step 8", "Impossible failure combinations",       "15 rows corrected — modes zeroed"),
]

print(f"{'Step':<8} {'Problem':<45} {'Fix'}")
print("-" * 85)
for step, prob, fix in changes:
    print(f"{step:<8} {prob:<45} {fix}")

Clean dataset saved: 10,000 rows × 19 columns

Step     Problem                                       Fix
-------------------------------------------------------------------------------------
Step 1   Whitespace in column names                    Stripped — 2 columns fixed
Step 2   Tool wear column dtype (object)               pd.to_numeric() — 'N/A' → NaN
Step 3   Missing sensor values (439 nulls)             ffill / median-per-type / interpolate
Step 4   Duplicate rows (pipeline resend)              Removed 60 duplicates
Step 5   Temperature unit error (K vs °C)              12 rows converted °C → K
Step 6   Physical outliers (calibration drift)         8 values clipped to IQR fences
Step 7   Inconsistent Type encoding                    30 values normalised to L/M/H
Step 8   Impossible failure combinations               15 rows corrected — modes zeroed

## Key analytical findings from cleaned data

This is the section a client reads. Not the code — the insights.

In [23]:
print("=" * 65)
print("  KEY FINDINGS — AI4I Predictive Maintenance Dataset")
print("=" * 65)

total = len(df_clean)
fail_n = df_clean['Machine failure'].sum()

print(f"\n1. Overall failure rate: {fail_n/total*100:.1f}% ({fail_n} events)")

print("\n2. Failure rate by machine type:")
for t, g in df_clean.groupby('Type'):
    r = g['Machine failure'].mean() * 100
    print(f"   Type {t}: {r:.1f}%")

print("\n3. Most common failure mode:")
mode_rates = {col: df_clean[col].sum() for col in ['TWF','HDF','PWF','OSF','RNF']}
top_mode = max(mode_rates, key=mode_rates.get)
print(f"   {top_mode}: {mode_rates[top_mode]} events")
print(f"   HDF events almost always occur at temp diff < 8.6K AND speed < 1380rpm")

print("\n4. Failure rate by tool wear stage:")
for stage, g in df_clean.groupby('Wear stage', observed=True):
    r = g['Machine failure'].mean() * 100
    print(f"   {stage}: {r:.1f}%  ← {'HIGH RISK' if r > 5 else 'normal'}")

print("\n5. Critical thresholds identified:")
print(f"   Torque > {fail['Torque [Nm]'].quantile(0.75):.1f} Nm → elevated failure risk")
print(f"   Speed < {fail['Rotational speed [rpm]'].quantile(0.25):.0f} rpm → elevated failure risk")
print(f"   Wear-torque product > 11,000 → OSF risk zone")

print()
print("=" * 65)

=================================================================
  KEY FINDINGS — AI4I Predictive Maintenance Dataset
=================================================================

1. Overall failure rate: 7.1% (715 events)

2. Failure rate by machine type:
   Type H: 7.6%
   Type L: 7.0%
   Type M: 7.0%

3. Most common failure mode:
   PWF: 586 events
   HDF events almost always occur at temp diff < 8.6K AND speed < 1380rpm

4. Failure rate by tool wear stage:
   early: 6.3%  ← HIGH RISK
   mid: 5.6%  ← HIGH RISK
   late: 9.7%  ← HIGH RISK

5. Critical thresholds identified:
   Torque > 47.2 Nm → elevated failure risk
   Speed < 1408 rpm → elevated failure risk
   Wear-torque product > 11,000 → OSF risk zone

=================================================================